# Generated by Django 4.1.3 on 2023-07-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_type', models.CharField(choices=[('dashboard', 'Dashboard'), ('webapp', 'Web App'), ('website', 'Website'), ('mobile', 'Mobile')], max_length=20)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
