# Generated by Django 4.1.3 on 2023-07-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='testimonial_images/')),
                ('quote', models.TextField()),
            ],
        ),
    ]
